### ISSUE TITLE
Sending data without ACK

### ISSUE THREAD

**Issue by Manur94** [nRF24/RF24Network#108]
hello, 

I am trying to establish a network with 255 receiver nodes.
but with only one sender, what is the best way to go about doing this?

i can't use the mesh function because i would need 'router' nodes witch is not possible with my setup.
i tried using 1 pipeline for all the receivers, and putting adres data in the payload, and making my own ack that get's send back to the sender.

But how do i disable the ack, are there different sorts of ack's that get send back for a normal payload?
or would i best use a different library all together?

Thanks in advance

**Comment by Avamander** [comment]
What do you mean "router nodes"? All nodes act as relays by default and only one (master) acts like a "router".
