### ISSUE TITLE
from master to node

### ISSUE THREAD

**Issue by guaracheitor** [nRF24/RF24Network#111]
Hi, first all, I would to thanks the work that you do with this library!

I have a RF24Network working well to send data from nodes to master. But now I need to send some data from master to certain node when these starts.  I have been trying RF24Mesh and RF24Network but I couldn't make it works.

Can you give me some clue?

Thanks in advance!
Inti

**Comment by guaracheitor** [comment]
to use read/write at/from the master node, do I need two radios?

**Comment by Avamander** [comment]
@guaracheitor No (to the last question).
