### ISSUE TITLE
Multicast Relay

### ISSUE THREAD

**Issue by MAKOMO** [nRF24/RF24Network#117]
If a node sends out a multicast to its children and those are configured to relay multicasts, assuming all nodes are running the same code, then they would send the relay message all at the exact same moment in time which will most certainly result in some collisions that cannot prevented on the node level code. Would it make sense to add a small delay based on a nodes address in this case, before sending out the relayed message?

```
if(multicastRelay){					
    IF_SERIAL_DEBUG_ROUTING( printf_P(PSTR("%u MAC: FWD multicast frame from 0%o to level %u\n"),millis(),header->from_node,multicast_level+1); );
    delayMicroseconds((node_address % 4)*700 + 700*4); // LINE ADDED
    write(levelToAddress(multicast_level)<<3,4);
}
```

This will not solve the problem in general, but at least avoid some certain collisions. Thoughts?

**Comment by TMRh20** [comment]
Merged pull req.
