### ISSUE TITLE
ImportError: No module named RF24Network

### ISSUE THREAD

**Issue by sourabhns** [nRF24/RF24Network#120]
when i'm trying to run helloworld_tx.py program in RPi it shows error every time, i installed mudule  using "wget http://tmrh20.github.io/RF24Installer/RPi/install.sh"  please give instruction to solve error

**Comment by TMRh20** [comment]
See http://TMRh20.github.io/RF24/Python.html

**Comment by vamsikrishnaA9** [comment]
@TMRh20 hi sir, after followed the steps in http://tmrh20.github.io/RF24/Python.html
.setup.py build command should be executed in which path ?? I didnt understood.
For 3,4 commands please mention path.
When i run the commands as it is it showing cant build file. I am new to rpi 
Please help
