### ISSUE TITLE
Python Wrapper Build Fails

### ISSUE THREAD

**Issue by cnlangness** [nRF24/RF24Network#126]
I believe the peek functionality that was implemented in pull #106 broke the Python wrapper. From the comments on that pull request, it does not appear that the Python wrapper was tested.

Using the latest from the repo, when building the Python wrapper, I get the following error:
```
pyRF24Network.cpp: In function ‘void init_module_RF24Network()’:
pyRF24Network.cpp:107:60: error: no matches converting function ‘peek’ to type ‘peek_function_type {aka void (class RF24Network::*)(struct RF24NetworkHeader&)}’
                 , peek_function_type( &::RF24Network::peek )
                                                            ^
In file included from pyRF24Network.cpp:3:0:
/usr/local/include/RF24Network/RF24Network.h:445:8: note: candidates are: void RF24Network::peek(RF24NetworkHeader&, void*, uint16_t)
   void peek(RF24NetworkHeader& header, void* message, uint16_t maxlen);
        ^~~~
/usr/local/include/RF24Network/RF24Network.h:432:12: note:                 uint16_t RF24Network::peek(RF24NetworkHeader&)
   uint16_t peek(RF24NetworkHeader& header);
            ^~~~
error: command 'gcc' failed with exit status 1
```

I checked out commit a2ce4aee1f94f742018b5b4d50665d9cbfb360b7 and reinstalled the library. Running `./setup.py build` is successful and the module is installed.

After removing the module and checking out commit ce128543b779eba0cdf59583404b42ce7e3eaa3b - which is the commit for PR #106, I reinstalled the library. Running `./setup.py build` results in the same error message as above.

I'll try my hand at a fix for this, but wanted to open an issue for this in case someone better at boost wants to tackle it.

**Comment by Avamander** [comment]
@cnlangness Feel free to open a PR with the change.

Though if the non-matching return types actually are an issue, why didn't it fail before? `peek` has been `uint16_t` for three years now.

**Comment by cnlangness** [comment]
@Avamander I will open a PR once I confirm that there aren't any adverse downstream effects from adding the `uint16_t`. 

I also plan on digging in to the reason that it is required now. I suspect it may be that during compilation before, there was only one option for `peek`, so there was no confusion. Now that there are multiple options, it may require more specificity.
