### ISSUE TITLE
Rpi perfomance

### ISSUE THREAD

**Issue by dimquea** [nRF24/RF24Network#130]
I made small programm for rpi 1. Programm read network, after receiving message from other node, make mysql query. 
All code in the while(1) cycle, like in example. And I see 100% CPU usage every time, even idle. 
So how I can reduce the load, without packet losing?
Thank you.

**Comment by wilmsn** [comment]
Even i don't know your sourcecode but as you are in a multitasking system you should always do something like this:
....
while(1) {
# do your job here
usleep(1000) #sleeptime in us. change it to whatever you can give the processor to other tasks
}

**Comment by dimquea** [comment]
I think about same. But how about radio? What happens when message will be arrived, but usleep still work?

**Comment by wilmsn** [comment]
Message will be buffered in the radio chip. You should choose a sleep time that makes sure that no messages go lost. Read the datasheet of nrf24l01 chips to get more information about build in registers.

**Comment by dimquea** [comment]
i checked your rf24hub. very interesting. thank you.
