### ISSUE TITLE
"Cannot enqueue multi-payload frames to self"

### ISSUE THREAD

**Issue by Esteves4** [nRF24/RF24Network#134]
Receving this message while running RF24Network on a Raspberry Pi. I receive this message four times and then I stop receiving packages. Can anyone help me understand what's happening?

**Comment by Esteves4** [comment]
It started yesterday. Doesn't happen very often but I'm not sending anything from the master node, just receiving. I was working with another master node in a different channel, could that interfere?

**Comment by TMRh20** [comment]
Seems like a good possibility.

**Comment by Esteves4** [comment]
Okay. Thanks for the help!
