### ISSUE TITLE
How to use multicast relay?

### ISSUE THREAD

**Issue by marcus011** [nRF24/RF24Network#137]
Hi, 
I need to broadcast message to same ID's, earlier I was using Rf24Network but having some issues with but as recommended by  @TMRh20 

> https://github.com/nRF24/RF24Network/issues/136#issuecomment-492577582

 to use multicast and multicast relay. But I have gone through the NRF Documents 

> [http://tmrh20.github.io/RF24Network/index.html](url) 

and didn't find any tutorial or great explanation of how to use this.

So can you help me how to use the multicast relay for broadcasting?

Thanks

**Comment by TMRh20** [comment]
If you take a look at the image [here](http://tmrh20.github.io/RF24Network/Tuning.html) , it shows the different 'levels' the network is divided into. 

For example, to send a broadcast message from the master node to all other nodes, just call [network.multicast()](http://tmrh20.github.io/RF24Network/classRF24Network.html#a25e19015dbf5073a8401e0fe71f68848) and send the data to 'level 1'

The nodes at level 1 (nodes 01 - 05) need to have multicast forwarding on if you want them to forward multicast messages over extended distances (to level 2, etc). For this, each node should have [multicast relay](http://tmrh20.github.io/RF24Network/classRF24Network.html#add7408ca2b2f9ab15331ba77a747f7bb) enabled.

Alternately, if all of the nodes are in range of the master, you can set them all to use the [same multicast 'level'](http://tmrh20.github.io/RF24Network/classRF24Network.html#a4fb7c61eee75d708a4ba20bb1caec54f) and no forwarding is required.

Hope that helps,

TMRh20

**Comment by marcus011** [comment]
Thanks @TMRh20 for replying, right now my all device is having same id i.e 01 and after your response, I have used this.
`  bool ok = network.multicast(header, &rm_payload, sizeof(rm_payload), 01);`
so can you tell will this work properly & did all my nodes with id 01 will receive the message?
and I don't want my data to shift to another level, I need only one level.

**Comment by TMRh20** [comment]
It might but technically you would want to set proper addressing and set the multicast level to one on each node per my previous message.

**Comment by Cyberstorm11** [comment]
Hi,
I have a network of adunios all running the RF24network library.

I am also trying to use the multicast function on 2 layers of devices. 
00 -> 01 -> 011
               -> 021 etc
When I turn on multicast relaying on node 01 it stops responding to the broadcast message.

Master Code snippet:
```
//Send the message
  network.update();
  RF24NetworkHeader header(01);     // (Address where the data is going)
  bool ok = network.multicast(header, &outData, sizeof(outData), level); // Send the data
  delayMicroseconds(500);
  if (level == 01) level = 02;
  else level = 01;
```
nodes
`    //NRF24
    SPI.begin();
    radio.setRetries(5, 15);
    network.txTimeout = 486 + this_node * 7;
    radio.begin();
    network.begin(55, this_node); //(channel, node address)
    network.multicastRelay = this_node < 9;//only layer one nodes multicast
`
It appears on node 01 the network.available() does not return true once multicast is enabled.
What have I missed?

Thanks for any help.

**Comment by TMRh20** [comment]
The issue is not apparent from your code. I would suggest turning on debugging (RF24Network_config.h) to get more info and double check ur code.

**Comment by Cyberstorm11** [comment]
Thanks for the replay I am getting serial information and have attached a dump from node01Debug Serial.

My limited understandings that duplicate messages appear to be filling the message buffer?
[Node01Debugfile.txt](https://github.com/nRF24/RF24Network/files/4498545/Node01Debugfile.txt)

**Comment by TMRh20** [comment]
That’s weird, looks like the multicast levels are messed up or something. I’m guessing it’s going to be something in your code. I haven’t gotten a chance to look closely at this but I’ll take a closer look as soon as I can.

**Comment by Cyberstorm11** [comment]
Thanks for your time below are both ends of the code its a bit messy being in development.

Master
`
#include <RF24.h>
#include <RF24Network.h>
#include <SPI.h>
#include "printf.h"

RF24 radio(7, 8);                // nRF24L01 (CE,CSN)
RF24Network network(radio);      // Include the radio in the network
const uint16_t this_node = 00;   // Address of this node in Octal format ( 04,031, etc)
const uint16_t node01 = 01, node011 = 011, node021 = 021, node031 = 031;
const uint16_t node02 = 02, node012 = 012, node022 = 022, node032 = 032;
const uint16_t node03 = 03, node013 = 013;

const int Number_ch = 14;// Number of LED channels being controlled

bool Serial_EN = true;// Enable or disable serial communications

uint8_t level = 01;

const int blinkPin = 2;//Blink Indication Pin
bool toggle;


//Serial Variables
String inputString = "";         // a string to hold incoming data
boolean stringComplete = false;  // whether the string is complete

//timer setup
unsigned long currentTime = 0;

//Timer Structure
struct timer {
  unsigned long lastTime;
  unsigned long interval;
  bool output;
};
timer timers[10];

//Channel Structures
struct channel {
  byte pwm;//Pulse Width value of channel 0 to 255
  bool side1; //Side 1 enabled
  bool side2; //Side 2 enabled
  bool change;// has the pattern changed
  byte pattern;//pattern assignment
  bool rampUp;//Current ramp direction is rising
  timer pTimers[5];//pattern timers
};

//Channel Declaration
channel ch[Number_ch];

//Network Data Structure
struct netData {
  byte data1;//PWM channel 1
  byte data2;//PWM channel 2
  byte data3;//Command Byte
  /*Command Byte
     0 = 0 all off
     0 = 1 enable other functions
     1 = 1 channel 1 side 1 On
     2 = 1 channel 1 side 2 On
     3 = 1 channel 2 side 1 On
     4 = 1 channel 2 side 2 On
     5 reserved
     6 reserved
     7 reserved
  */
};

struct outMsg {
  netData node[7];
};
outMsg outData;
  
//Variables
bool mode;

void setup() {
  //NRF24
  SPI.begin();
  radio.setRetries(1, 15);
  network.txTimeout = 261;
  radio.begin();
  network.begin(55, this_node); //(channel, node address)

  //Serial
  if (Serial_EN) {
    Serial.begin(115200);
    inputString.reserve(200);
    Serial.println("Light Master 2.0");
    printf_begin();
  }


  for (int i = 0; i < Number_ch; i ++) {
    ch[i].pwm = 255;
  }

  //Timers
  timers[0].interval = 500;// one second timer
  timers[1].interval = 10000;//10 second mode change
  timers[2].interval = 1000;//BLINK TIMER
}
void loop() {
  //Timer function requirement
  currentTime = millis();

  //Serial Checking
  if (Serial_EN) serialCheck();

  if (checkTimer(1)) {
    mode = !mode;
  }
  if (mode) {
    if (checkTimer(0)) {
      toggle = !toggle;
      for (int i = 0; i < Number_ch; i ++) {
        ch[i].side1 = toggle;
        ch[i].side2 = !toggle;
      }
      /*ch[6].side1 = !ch[6].side1;
        ch[6].side2 = !ch[6].side2;
        ch[7].side1 = !ch[7].side1;
        ch[7].side2 = !ch[7].side2;*/
    }
  }
  else {
    if (checkTimer(0)) {
      toggle = !toggle;
      for (int i = 0; i < Number_ch; i = i + 2) {
        int j = i + 1;
        ch[i].side1 = toggle;
        ch[i].side2 = toggle;
        ch[j].side1 = !toggle;
        ch[j].side2 = !toggle;
      }
      /*ch[6].side1 = !ch[6].side1;
        ch[6].side2 = !ch[6].side2;
        ch[7].side1 = !ch[7].side1;
        ch[7].side2 = !ch[7].side2;*/
    }
  }


  if (checkTimer(2)) {
    bool temp = digitalRead(blinkPin);
    if (temp) digitalWrite(blinkPin, LOW);
    else digitalWrite(blinkPin, HIGH);
  }


  //Prepare Command Byte
  byte cmd;
  bitWrite(cmd, 0, 1); //enable node
  bitWrite(cmd, 1, ch[0].side1);
  bitWrite(cmd, 2, ch[0].side2);
  bitWrite(cmd, 3, ch[1].side1);
  bitWrite(cmd, 4, ch[1].side2);

  //Copy channels to do the same
  copy_ch(0, 2);
  copy_ch(1, 3);
  copy_ch(0, 4);
  copy_ch(1, 5);
  copy_ch(0, 6);
  copy_ch(1, 7);
  copy_ch(0, 8);
  copy_ch(1, 9);
  copy_ch(0, 10);
  copy_ch(1, 11);
  copy_ch(0, 12);
  copy_ch(1, 13);


  // Prepare messages

  for (int i = 0; i < Number_ch; i = i + 2) {
    int j = i + 1;
    int k = i / 2;
    //Prepare Command Byte
    byte cmd;
    bitWrite(cmd, 0, ch[i].pwm > 0 || ch[j].pwm > 0); //enable node
    bitWrite(cmd, 1, ch[i].side1);
    bitWrite(cmd, 2, ch[i].side2);
    bitWrite(cmd, 3, ch[j].side1);
    bitWrite(cmd, 4, ch[j].side2);
    // Prepare out Data
    outData.node[k] = {ch[i].pwm, ch[j].pwm, cmd};
  }
  //Send the message
  network.update();
  RF24NetworkHeader header(01);     // (Address where the data is going)
  bool ok = network.multicast(header, &outData, sizeof(outData), level); // Send the data
  delayMicroseconds(20000);
//ok = network.multicast(header, &outData, sizeof(outData), 02); // Send the data
  //delayMicroseconds(100);
  if (level == 01) level = 01;
  else level = 01;
} // END LOOP


void serialEvent() {
  if (Serial_EN) {
    while (Serial.available()) {
      // get the new byte:
      char inChar = (char)Serial.read();
      // add it to the inputString:
      inputString += inChar;
      // if the incoming character is a newline, set a flag
      // so the main loop can do something about it:
      if (inChar == '\n') {
        stringComplete = true;
      }
    }
  }
}

void serialCheck()
{
  if (stringComplete) {
    Serial.print("Received: ");
    Serial.println(inputString);
    if (inputString.startsWith("a")) {
      inputString.replace("a", "");
      ch[0].pwm = (byte)inputString.toInt();
    }
    else if (inputString.startsWith("b")) {
      inputString.replace("b", "");
      ch[1].pwm = inputString.toInt();
    }
    else if (inputString.startsWith("?")) {
      Serial.print("Number of Channels: ");
      Serial.println(Number_ch);
      for (int x = 0; x < Number_ch; x++) {
        dataString(x);
      }
    }
    else if (inputString.startsWith("/")) {
      Serial.print("Number of Nodes: ");
      Serial.println(Number_ch/2);
      for (int x = 0; x < Number_ch/2; x++) {
        dataString2(x);
      }
    }
    else Serial.println("Invalid instruction!");
    inputString = "";
    stringComplete = false;

  }
}

boolean checkTimer(byte timerN) {
  if (currentTime - timers[timerN].lastTime > timers[timerN].interval || timers[timerN].lastTime > currentTime) {
    timers[timerN].lastTime = currentTime;
    return true;
  }
  else return false;
}

void dataString(int index) {
  Serial.print("------ Channel: ");
  Serial.println(index);
  String a, b;
  a =  String("PWM:");
  b = String(ch[index].pwm, DEC);
  a = String(a + b);
  a = String(a + " Side 1: ");
  b = String(ch[index].side1, DEC);
  a = String(a + b);
  a =  String(a + " Side 2: ");
  b = String(ch[index].side2, DEC);
  a = String(a + b);
  Serial.println(a);
}

void dataString2(int index){
  Serial.print("------ Node: ");
  Serial.println(index);
  String a, b;
  a =  String("PWM1:");
  b = String(outData.node[index].data1, DEC);
  a = String(a + b);
  a = String(a + " PWM2: ");
  b = String(outData.node[index].data2, DEC);
  a = String(a + b);
  a =  String(a + " CMD: ");
  b = String(outData.node[index].data3, BIN);
  a = String(a + b);
  Serial.println(a);
}

void copy_ch(int source, int dest) {
  ch[dest].pwm = ch[source].pwm;
  ch[dest].side1 = ch[source].side1;
  ch[dest].side2 = ch[source].side2;
}
`
Node
`#include <RF24.h>
#include <RF24Network.h>
#include <SPI.h>
#include "printf.h"

//RF Variables
RF24 radio(7, 8);               // nRF24L01 (CE,CSN)
RF24Network network(radio);      // Include the radio in the network
const uint16_t this_node = 01;   // Address of our node in Octal format ( 04,031, etc)
const int hWare = 2; //Shield Hardware Version number
const int node_pos = 0; // node message position (array position data)

const bool Serial_EN = true;

long rfCount = 0;               //Count when no signal received
int blinkPin = 2;               //Blink indication pin number

//Serial Variables
String inputString = "";         // a string to hold incoming data
boolean stringComplete = false;  // whether the string is complete

//timer setup
unsigned long currentTime = 0;
unsigned long time[20][2];// [x][0] = last time, [x][1] = interval

//LED Structure
struct LED {
  byte pwm;
  bool side;
  byte PIN_EN;
  byte PIN_1;
  byte PIN_2;
};

LED channel_1 = {0, 0, 5, 10, 9}; //pwm, side, PIN_EN, PIN_1, PIN_2
LED channel_2 = {0, 0, 3, 6, 4}; //pwm, side, PIN_EN, PIN_1, PIN_2

//Command byte bit variables
byte cmByte;
bool enable, channel_1_s1, channel_1_s2, channel_2_s1, channel_2_s2;

//Network Data Structure
struct netData {
  byte data1;//PWM channel 1
  byte data2;//PWM channel 2
  byte data3;//Command Byte
  /*Command Byte
     0 = 0 all off
     0 = 1 enable other functions
     1 = 1 channel 1 side 1 On
     2 = 1 channel 1 side 2 On
     3 = 1 channel 2 side 1 On
     4 = 1 channel 2 side 2 On
     5 reserved
     6 reserved
     7 reserved
  */
};

//Network Message Structure
struct inMsg {
  netData node[7];
};
inMsg inData;

boolean checkTimer(byte timerN) {
  if (currentTime - time[timerN][0] > time[timerN][1] || time[timerN][0] > currentTime) {
    time[timerN][0] = currentTime;
    return true;
  }
  else return false;
}

void version_1() { //VERSION 1 HARDWARE LOGIC
  //Channel 1 logic
  if (channel_1.pwm > 0) { // If channel is active
    analogWrite(channel_1.PIN_EN, channel_1.pwm);
    if (channel_1_s1 && channel_1_s2) { // If both sides are requested switch both regularly
      if (checkTimer(1)) {
        if (channel_1.side) {
          digitalWrite(channel_1.PIN_1, !channel_1.side);
          digitalWrite(channel_1.PIN_2, channel_1.side);
          channel_1.side = 0;
        }
        else {
          digitalWrite(channel_1.PIN_2, channel_1.side);
          digitalWrite(channel_1.PIN_1, !channel_1.side);
          channel_1.side = 1;
        }
      }
    }
    else { // Just write the data to the enable pins
      digitalWrite(channel_1.PIN_1, channel_1_s1);
      digitalWrite(channel_1.PIN_2, channel_1_s2);
    }
  }
  else analogWrite(channel_1.PIN_EN, 0);

  //Channel 2 logic
  if (channel_2.pwm > 0) { // If channel is active
    analogWrite(channel_2.PIN_EN, channel_2.pwm);
    if (channel_2_s1 && channel_2_s2) { // If both sides are requested switch both regularly
      if (checkTimer(2)) {
        if (channel_2.side) {
          digitalWrite(channel_2.PIN_1, !channel_2.side);
          digitalWrite(channel_2.PIN_2, channel_2.side);
          channel_2.side = 0;
        }
        else {
          digitalWrite(channel_2.PIN_2, channel_2.side);
          digitalWrite(channel_2.PIN_1, !channel_2.side);
          channel_2.side = 1;
        }
      }
    }
    else { // Just write the data to the enable pins
      digitalWrite(channel_2.PIN_1, channel_2_s1);
      digitalWrite(channel_2.PIN_2, channel_2_s2);
    }
  }
  else analogWrite(channel_2.PIN_EN, 0);
}

void networkCheck() {
  network.update();
  while ( network.available() ) {     // Is there any incoming data?
    RF24NetworkHeader header;
    network.read(header, &inData, sizeof(inData)); // Read the incoming data
    netData incomingData;
    incomingData = inData.node[node_pos];

    channel_1.pwm = incomingData.data1;
    channel_2.pwm = incomingData.data2;
    cmByte = incomingData.data3;


    enable = bitRead(cmByte, 0);
    channel_1_s1 = bitRead(cmByte, 1);
    channel_1_s2 = bitRead(cmByte, 2);
    channel_2_s1 = bitRead(cmByte, 3);
    channel_2_s2 = bitRead(cmByte, 4);

    rfCount = 0;
  }
  if (rfCount <= 60000) rfCount ++;//Failed to receive data counter

  //LED BLINK INDICATOR
  if (checkTimer(0)) {
    bool temp = digitalRead(blinkPin);
    if (temp) digitalWrite(blinkPin, LOW);
    else digitalWrite(blinkPin, HIGH);
    //Serial.print("RF Count: ");
    //Serial.println(rfCount);
  }
}

void serialEvent() {
  while (Serial.available()) {
    // get the new byte:
    char inChar = (char)Serial.read();
    // add it to the inputString:
    inputString += inChar;
    // if the incoming character is a newline, set a flag
    // so the main loop can do something about it:
    if (inChar == '\n') {
      stringComplete = true;
    }
  }
}

void dataString2(int index) {
    Serial.print("------ Node: ");
    Serial.println(index);
    String a, b;
    a =  String("PWM1:");
    b = String(inData.node[index].data1, DEC);
    a = String(a + b);
    a = String(a + " PWM2: ");
    b = String(inData.node[index].data2, DEC);
    a = String(a + b);
    a =  String(a + " CMD: ");
    b = String(inData.node[index].data3, BIN);
    a = String(a + b);
    Serial.println(a);
  }
void serialCheck()
{
  if (stringComplete) {
    if (inputString.startsWith("a")) {
      inputString.replace("a", "");
      channel_1.pwm = inputString.toInt();

      Serial.println(channel_1.pwm);
      delay(500);
    }
    else if (inputString.startsWith("b")) {
      inputString.replace("b", "");
      channel_2.pwm = inputString.toInt();

      Serial.println(channel_1.pwm);
      delay(500);
    }
    else if (inputString.startsWith("/")) {
      Serial.print("Number of Nodes: ");
      Serial.println(10);
      for (int x = 0; x < 10; x++) {
        dataString2(x);
      }

    }
    inputString = "";
    stringComplete = false;
  }
}

//Software reset Ardunio
//void(* resetFunc) (void) = 0; //declare reset function @ address 0

  void setup() {
    //Static Timers
    time[0][1] = 1000; //1 second timer
    time[1][1] = 1; //Channel 1 both on swap timer
    time[2][1] = 1; //Channel 2 both on swap timer
    time[3][1] = 450; // RF data to serial rate

    //PIN SETUP
    pinMode(channel_1.PIN_EN, OUTPUT);
    pinMode(channel_1.PIN_1, OUTPUT);
    pinMode(channel_1.PIN_2, OUTPUT);
    pinMode(channel_2.PIN_EN, OUTPUT);
    pinMode(channel_2.PIN_1, OUTPUT);
    pinMode(channel_2.PIN_2, OUTPUT);
    pinMode(blinkPin, OUTPUT);

    //Serial
    if (Serial_EN) {
      Serial.begin(115200);
      inputString.reserve(200);
      Serial.print("Light Node Hardware V");
      Serial.println(hWare);
      Serial.print("Node Address: ");
      String a = String(this_node, OCT);
      Serial.println(a);
      printf_begin();
    }

    //NRF24
    SPI.begin();
    radio.setRetries(5, 15);
    network.txTimeout = 486 + this_node * 7;
    radio.begin();
    network.begin(55, this_node); //(channel, node address)
    network.multicastRelay = true;//this_node < 06;
  }

  void loop() {
    currentTime = millis();
    networkCheck();
    //if (Serial_EN) serialCheck();
    
    //If not enabled or network fails for x no of requests turn off
    if (enable || rfCount < 60000) {
      if (hWare == 1) version_1();//VERSION 1 HARDWARE LOGIC
      else { //VERSION 2 HARDWARE LOGIC
        //Channel 1 logic
        if (channel_1.pwm > 0) { // If channel is active
          if (channel_1_s1 || channel_1_s2) analogWrite(channel_1.PIN_EN, channel_1.pwm);
          else analogWrite(channel_1.PIN_EN, 0);
          if (channel_1_s1 && channel_1_s2) { // If both sides are requested switch both regularly
            analogWrite(channel_1.PIN_1, 127);
          }
          else if (channel_1_s1) {
            analogWrite(channel_1.PIN_1, 255);
          }
          else if (channel_1_s2) {
            analogWrite(channel_1.PIN_1, 0);
          }
        }
        else analogWrite(channel_1.PIN_EN, 0);

        //Channel 2 logic
        if (channel_2.pwm > 0) { // If channel is active
          if (channel_2_s1 || channel_2_s2) analogWrite(channel_2.PIN_EN, channel_2.pwm);
          else analogWrite(channel_2.PIN_EN, 0);
          if (channel_2_s1 && channel_2_s2) { // If both sides are requested switch both regularly
            analogWrite(channel_2.PIN_1, 127);
          }
          else if (channel_2_s1) {
            analogWrite(channel_2.PIN_1, 255);
          }
          else if (channel_2_s2) {
            analogWrite(channel_2.PIN_1, 0);
          }
        }
        else analogWrite(channel_2.PIN_EN, 0);

      }
    }
    else if (rfCount > 61000){
      if (Serial_EN) Serial.println(rfCount);
     // resetFunc();  //call reset
    }
    else {
      analogWrite(channel_1.PIN_EN, 0);
      analogWrite(channel_2.PIN_EN, 0);
    }
  }
  // END OF LOOP
`

**Comment by TMRh20** [comment]
Not sure what to say here, I get different results. The queue doesn't seem to fill up, and the forwarding appears to be working.  
  
I notice my debug output is messed up a bit and reporting incorrect values when running your code, so without analyzing further I'm guessing you have a memory issue or something going on. (overwriting a buffer or something)  
  
One thing you should change in your code is to not configure the radio or network until calling radio.begin and network.begin.

My best suggestion would be to comment out large portions of your code and re-test until you get something that works. Then build from there and keep track of where it goes bad.
