### ISSUE TITLE
How to use RF24network sleep mode in ESP32

### ISSUE THREAD

**Issue by mixaobo** [nRF24/RF24Network#139]
I' m doing RF24network in ESP32. I'm only do with esp32 now (not download any arduino or esp8266 library) and have trouble with sleep_mode. i have uncomment endable_sleep_mode in config file and got this `C:\Users\Admin\Documents\Arduino\libraries\RF24Network\RF24Network.cpp:35:24: fatal error: avr/sleep.h: No such file or directory`
i have downloaded avr-libc-master but dont know where should i put this library.
Thank you

**Comment by TMRh20** [comment]
The built in sleep mode only works with AVR devices, with ESP, you need to use ESP specific sleep modes. See 
https://www.google.ca/amp/s/lastminuteengineers.com/esp32-sleep-modes-power-consumption/amp/

**Comment by mixaobo** [comment]
I see. In RF24.h, there are powerup() and powerdown() function. Do i have to use it. Like
Powerdown();
Esp sleep like you post above;
Pơerup()

**Comment by mixaobo** [comment]
> The built in sleep mode only works with AVR devices, with ESP, you need to use ESP specific sleep modes. See https://www.google.ca/amp/s/lastminuteengineers.com/esp32-sleep-modes-power-consumption/amp/
> […](#)
> On Jun 25, 2019, at 02:47, mixaobo ***@***.***> wrote: I' m doing RF24network in ESP32. I'm only do with esp32 now (not download any arduino or esp8266 library) and have trouble with sleep_mode. i have uncomment endable_sleep_mode in config file and got this C:\Users\Admin\Documents\Arduino\libraries\RF24Network\RF24Network.cpp:35:24: fatal error: avr/sleep.h: No such file or directory i have downloaded avr-libc-master but dont know where should i put this library. Thank you — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I see. In RF24.h, there are powerup() and powerdown() function. Do i have to use it. Like
Powerdown();
Esp sleep like you post above;
Powerup();

**Comment by TMRh20** [comment]
Uhh, no you have to use ESP specific code. Google for ESP32 low power modes.

**Comment by mixaobo** [comment]
> Uhh, no you have to use ESP specific code. Google for ESP32 low power modes.
> […](#)
> On Jun 25, 2019, at 05:09, mixaobo ***@***.***> wrote: The built in sleep mode only works with AVR devices, with ESP, you need to use ESP specific sleep modes. See https://www.google.ca/amp/s/lastminuteengineers.com/esp32-sleep-modes-power-consumption/amp/ … On Jun 25, 2019, at 02:47, mixaobo @.***> wrote: I' m doing RF24network in ESP32. I'm only do with esp32 now (not download any arduino or esp8266 library) and have trouble with sleep_mode. i have uncomment endable_sleep_mode in config file and got this C:\Users\Admin\Documents\Arduino\libraries\RF24Network\RF24Network.cpp:35:24: fatal error: avr/sleep.h: No such file or directory i have downloaded avr-libc-master but dont know where should i put this library. Thank you — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. I see. In RF24.h, there are powerup() and powerdown() function. Do i have to use it. Like Powerdown(); Esp sleep like you post above; Powerup(); — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Thank you. Close issue
