### ISSUE TITLE
How would you use this library in Qt 5 ?

### ISSUE THREAD

**Issue by csaba911** [nRF24/RF24Network#140]
Working fine with Arduino and all examples, made a few C++ test program and works very well (Thanks for making it)
Now I would like to use it with Qt5 GUI so it can actually display data/text in a app other than just in the terminal. I'm novice with Linux and Qt so could be just a beginners error.
 RF24 *radio = new RF24(RPI_V2_GPIO_P1_22, BCM2835_SPI_CS0, BCM2835_SPI_SPEED_4MHZ);
radio->begin();

radio->setDataRate(RF24_2MBPS);

radio->setChannel(0);

radio->setCRCLength(RF24_CRC_16);

radio->disableDynamicPayloads();

radio->setPayloadSize(32);

radio->setPALevel(RF24_PA_LOW);

Haven't done anything else as fail to build, 
Severity	Code	Description	Project	File	Line	Suppression State
Error		undefined reference to `RF24::RF24(unsigned short, unsigned short, unsigned int)'	RF4	D:\PiProjects\RF4\RF4\MainWindow.cpp	48	
Any advice or example for Qt4/5 ?

**Comment by Avamander** [comment]
You have to import all the same libraries as in the test code, your current error is quite literally that RF24::RF24 can't be found.
