### ISSUE TITLE
Fragmentation/Reassembly of payloads using RF24Network.write() and RF24Network.read() functions?

### ISSUE THREAD

**Issue by hanishgopi** [nRF24/RF24Network#147]
I have fragmented my 93 bytes long payload to three parts like 31,31,31 at the transmitter node and sending them to master using RF24Network.write(header,&payload1,sizeof(payload1));
RF24Network.write(header,&payload2,sizeof(payload2));
RF24Network.write(header,&payload3,sizeof(payload3)).

At the receiver node, Im reading the payload using:
RF24Network.read(header,&incoming Data , size of(incoming Data));
this goes into void loop(), so that I can continuously get what transmitter is sending and here comes the issue... I can only receive the 1st payload i.e payload1 from transmitter, so I thought of adding delay in the receiver code and tried receiving...and obtained remaining two payloads …..but is there any other way to get data at the received node without using any delay ….. HOW TO REASSEMBLE ? please suggest me any solution...   @TMRh20    ….I got struck here from past one week.....

**Comment by TMRh20** [comment]
Don’t fragment your payloads. The library handles it automatically.
