### ISSUE TITLE
Sending more than 28bytes from slave to master Resets the master..!!

### ISSUE THREAD

**Issue by hanishgopi** [nRF24/RF24Network#151]
Im using Atmega328p barebone as slave(Tx) and Arduino Mega as Master(Rx) … 
For every 2 seconds slave sends payload of 10 bytes to master this works perfectly fine.
but when I increase the payload size and send for every 2 seconds ...the master receives it and resets automatically.....if anyone solved this problem plz suggest me ...Thank you @TMRh20 @Avamander @maniacbug

**Comment by 2bndy5** [comment]
what do you mean "resets automatically"? What variant of of the nRF24L01 are you using? What does your code look like? We simply need more information to even try to diagnose this.
