### ISSUE TITLE
Can the unique identifier for nrf24mesh be more than 255 

### ISSUE THREAD

**Issue by Karlhenry** [nRF24/RF24Network#152]
I am planning on doing a project that uses nrf24mesh in setting up a network with many nodes(up to 500 nodes ),and I want a physical movement for  each node .@ Tmrh20

**Comment by TMRh20** [comment]
The mesh will realistically only handle say from 15-25 nodes depending on traffic generated etc.

Up to 500 nodes would require a much more robust radio device.
