### ISSUE TITLE
Is Node MCU Supported?

### ISSUE THREAD

**Issue by 0-3-6-9** [nRF24/RF24Network#164]

**Comment by 2bndy5** [comment]
If you're asking if the nRF24L01 radio can communicate to the nodeMCU's WiFi radio, then then short answer is no.

[I've already posted a reply to the same question in the RF24 repo](https://github.com/nRF24/RF24/discussions/695#discussioncomment-199672), but I assumed you were asking if the RF24 library will work on the nodeMCU using the nRF24L01 radio (not the ESP8266 WiFi radio). 

It helps to have a detailed description or some kind of context when asking questions.
