### ISSUE TITLE
Are some networkFlags deprecated?

### ISSUE THREAD

**Issue by 2bndy5** [nRF24/RF24Network#185]
I can't find any reference in any of the RF24* libs using the `FLAG_BYPASS_HOLDS` & `FLAG_HOLD_INCOMING` values.

I blindly ported the `networkFlags` to pure python, but I'm only using the `FLAG_NO_POLL` in my RF24Mesh class. 😆

**Comment by TMRh20** [comment]
Those should probably be removed, from some experimental code.

**Comment by 2bndy5** [comment]
no objections to that. It would actually grant any external system built on RF24Network more room for custom flags.

**Comment by 2bndy5** [comment]
It will look kinda weird in the docs that only bit positions 2 & 3 are used in the `networkFlags` member, but I've grown unusually comfortable with awkwardness like that.

**Comment by TMRh20** [comment]
Hahaha, yeah I’m a messy coder. :/

**Comment by 2bndy5** [comment]
I have worked with much worse...
