### ISSUE TITLE
use graphviz to generate the octal addressing "graph"

### ISSUE THREAD

**Issue by 2bndy5** [nRF24/RF24Network#188]
I'm working on getting this repo's docs generated in Sphinx, but MD-embedded tables tend to have problems with sphinx. Most tables weem to work fine, but there is 1 table in the docs main page that is better suited as an actual graph rather than a table, namely the table in "Octal Addressing and Topology" section. Observe:
### generated in doxygen
![image](https://user-images.githubusercontent.com/14963867/139376062-10a5a4eb-0e14-414d-a8be-eac0ff6449d6.png)

### generated in sphinx (via `breathe` extension - so using the same source)
![image](https://user-images.githubusercontent.com/14963867/139376155-eb82eaa3-b647-4794-8258-69585212f003.png)

Notice the vertical "headers" are not shown. Also table cells don't use a vertical border (only horizontal border) due to Material Design concepts.

## Solution
Enter [Graphviz](https://graphviz.org/)! I've used this tool to generate graphs in the CirPy lib when documenting the network topology. Sphinx has native integration with Graphviz, meaning the graph's source code can be directly typed into the rST file used to generate Sphinx docs. Unfortunately, Doxygen's integration with Graphviz is limited to only HTML output (which looks horrible in github's MD renderer); the XML output doesn't behave well with the `breathe` extension. So in our use case, for Doxygen to make use of a graph drawn with Graphviz, it must be imported like a picture ☹️ (preferably an SVG).

My recommendation is to just use a png (or svg) generated from a similar source code that I threw together for the CirPy lib's topology page. The addresses were modified to use C++ octal representation.

[An interactive demonstration](http://magjac.com/graphviz-visual-editor/?dot=%20%20%20%20graph%20network_hierarchy%20%7B%0A%20%20%20%20%20%20%20%20bgcolor%3D%22%23323232A1%22%0A%20%20%20%20%20%20%20%20newrank%3Dtrue%0A%20%20%20%20%20%20%20%20%2F%2F%20ratio%3D%220.65%22%0A%20%20%20%20%20%20%20%20node%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20fontcolor%3D%22%23FEFEFE%22%0A%20%20%20%20%20%20%20%20%20%20%20%20fontsize%3D14%0A%20%20%20%20%20%20%20%20%20%20%20%20fontname%3DArial%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20pad%3D%220%22%0A%20%20%20%20%20%20%20%20margin%3D%220%22%0A%20%20%20%20%20%20%20%20subgraph%20cluster_hierarchy%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20bgcolor%3D%22%2324242400%22%0A%20%20%20%20%20%20%20%20%20%20%20%20color%3D%22%2324242400%22%0A%20%20%20%20%20%20%20%20%20%20%20%20node%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20style%3Dfilled%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20color%3D%22%23FEFEFE7f%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20edge%20%5Bcolor%3D%22%23FEFEFE%22%20style%3D%22setlinewidth%282%29%22%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20subgraph%20lvl_0%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2200%22%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20shape%3D%22circle%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20style%3D%22radial%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fillcolor%3D%220.85%3A%23018268%3B0%3A%23000%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20subgraph%20lvl_1%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20node%20%5Bfillcolor%3D%22%233E0180%22%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2201%22%20%2202%22%20%2203%22%20%2204%22%20%2205%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20subgraph%20lvl_2%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20node%20%5Bfillcolor%3D%22%23014B80%22%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22014%22%20%22024%22%20%22034%22%20%22044%22%20%22054%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20subgraph%20lvl_3%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20node%20%5Bfillcolor%3D%22%230E6902%22%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%220124%22%20%220224%22%20%220324%22%20%220424%22%20%220524%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20subgraph%20lvl_4%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20node%20%5Bfillcolor%3D%22%2380010B%22%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2201324%22%20%2202324%22%20%2203324%22%20%2204324%22%20%2205324%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2200%22%20--%20%2204%22%20--%20%22024%22%20--%20%220324%22%20--%20%2201324%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%2200%22%20--%20%2201%22%3B%20%2200%22%20--%20%2202%22%3B%20%2200%22%20--%20%2203%22%3B%20%2200%22%20--%20%2205%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%2204%22%20--%20%22014%22%3B%20%2204%22%20--%20%22034%22%3B%20%2204%22%20--%20%22044%22%3B%20%2204%22%20--%20%22054%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%22024%22%20--%20%220124%22%3B%20%22024%22%20--%20%220224%22%3B%20%22024%22%20--%20%220424%22%3B%20%22024%22%20--%20%220524%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%220324%22%20--%20%2202324%22%3B%20%220324%22%20--%20%2203324%22%3B%20%220324%22%20--%20%2204324%22%3B%20%220324%22%20--%20%2205324%22%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20subgraph%20cluster_legend%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20bgcolor%3D%22%23242424%22%0A%20%20%20%20%20%20%20%20%20%20%20%20color%3D%22%2324242400%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%22Legend%22%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20color%3D%22%23FEF9A9%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20shape%3Dplain%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20margin%3D0%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20label%3D%3C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTABLE%20CELLBORDER%3D%220%22%20CELLSPACING%3D%228%22%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTR%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTD%20BORDER%3D%221%22%20SIDES%3D%22B%22%20COLSPAN%3D%223%22%3ELegend%3C%2FTD%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FTR%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTR%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTD%3ENetwork%20Level%200%3C%2FTD%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTD%20BORDER%3D%221%22%20STYLE%3D%22rounded%2Cradial%22%20BGCOLOR%3D%22%23000%3A%23018268%22%3E%20%20%20%20%20%20%20%20%3C%2FTD%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FTR%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTR%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTD%3ENetwork%20Level%201%3C%2FTD%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTD%20BORDER%3D%221%22%20STYLE%3D%22rounded%22%20BGCOLOR%3D%22%233E0180%22%3E%20%20%20%20%20%20%20%20%3C%2FTD%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FTR%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTR%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTD%3ENetwork%20Level%202%3C%2FTD%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTD%20BORDER%3D%221%22%20STYLE%3D%22rounded%22%20BGCOLOR%3D%22%23014B80%22%3E%20%20%20%20%20%20%20%20%3C%2FTD%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FTR%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTR%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTD%3ENetwork%20Level%203%3C%2FTD%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTD%20BORDER%3D%221%22%20STYLE%3D%22rounded%22%20BGCOLOR%3D%22%230E6902%22%3E%20%20%20%20%20%20%20%20%3C%2FTD%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FTR%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTR%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTD%3ENetwork%20Level%204%3C%2FTD%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTD%20BORDER%3D%221%22%20STYLE%3D%22rounded%22%20BGCOLOR%3D%22%2380010B%22%3E%20%20%20%20%20%20%20%20%3C%2FTD%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FTR%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTR%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTD%20BORDER%3D%221%22%20SIDES%3D%22T%22%20COLSPAN%3D%223%22%3ENodes%20are%20labeled%3CBR%2F%3Ein%20octal%20numbers%3C%2FTD%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FTR%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FTABLE%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A).

Or [a more exact replica of the original table](http://magjac.com/graphviz-visual-editor/?dot=%20%20%20%20graph%20network_hierarchy%20%7B%0A%20%20%20%20%20%20%20%20bgcolor%3D%22%23323232A1%22%0A%20%20%20%20%20%20%20%20newrank%3Dtrue%0A%20%20%20%20%20%20%20%20%2F%2F%20ratio%3D%220.65%22%0A%20%20%20%20%20%20%20%20node%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20fontcolor%3D%22%23FEFEFE%22%0A%20%20%20%20%20%20%20%20%20%20%20%20fontsize%3D14%0A%20%20%20%20%20%20%20%20%20%20%20%20fontname%3DArial%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20subgraph%20cluster_hierarchy%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20style%20%3D%20rounded%0A%20%20%20%20%20%20%20%20%20%20%20%20bgcolor%3D%22%2324242400%22%0A%20%20%20%20%20%20%20%20%20%20%20%20color%3D%22%2324242400%22%0A%20%20%20%20%20%20%20%20%20%20%20%20fontcolor%20%3D%20%22%23FEF9A9%22%0A%20%20%20%20%20%20%20%20%20%20%20%20node%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20style%3D%22filled%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20color%3D%22%23FEFEFE7f%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20edge%20%5Bcolor%3D%22%23FEFEFE%22%20style%3D%22setlinewidth%282%29%22%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20subgraph%20cluster_lvl_0%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20label%20%3D%20%22Network%20Level%200%20%28master%20node%29%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20bgcolor%20%3D%20%22%23383838%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2000%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20shape%3D%22circle%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20style%3D%22radial%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fillcolor%3D%220.85%3A%23018268%3B0%3A%23000%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20subgraph%20cluster_lvl_1%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20label%20%3D%20%22Network%20Level%201%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20labeljust%3D%22l%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20pad%3D%2215%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20bgcolor%20%3D%20%22%23383838%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20node%20%5Bfillcolor%3D%22%233E0180%22%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2001%2004%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20subgraph%20cluster_lvl_2%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20label%20%3D%20%22Network%20Level%202%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20bgcolor%20%3D%20%22%23383838%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20node%20%5Bfillcolor%3D%22%23014B80%22%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20014%20021%20011%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20subgraph%20cluster_lvl_3%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20label%20%3D%20%22Network%20Level%203%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20bgcolor%20%3D%20%22%23383838%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20node%20%5Bfillcolor%3D%22%230E6902%22%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%200111%200121%200221%200114%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20subgraph%20cluster_lvl_4%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20label%20%3D%20%22Network%20Level%204%20%28highest%29%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20labelloc%3D%22b%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20labeljust%3D%22l%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20style%20%3D%20rounded%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20bgcolor%20%3D%20%22%23383838%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20node%20%5Bfillcolor%3D%22%2380010B%22%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2001221%2001114%2002114%2003114%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%2000%20--%2004%20--%20014%20--%200114%20--%2001114%0A%20%20%20%20%20%20%20%20%20%20%20%2000%20--%2001%20--%20011%20--%200111%0A%20%20%20%20%20%20%20%20%20%20%20%2001%20--%20021%20--%200121%0A%20%20%20%20%20%20%20%20%20%20%20%20021%20--%200221%20--%2001221%0A%20%20%20%20%20%20%20%20%20%20%20%200114%20--%2002114%0A%20%20%20%20%20%20%20%20%20%20%20%200114%20--03114%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A).

**Comment by 2bndy5** [comment]
FYI, I went with a more exact replica graph because the preceding paragraph talked specifically about the addresses depicted in the graph (or what used to be a table).

See the graph [hosted on RTD.org](https://rf24network.readthedocs.io/en/latest/#index_1autotoc_md15) or [in github directly](https://github.com/nRF24/RF24Network/blob/CMake-4-Linux/docs/main_page.md#octal-addressing-and-topology). This will also show in doxygen when gh-pages get updated.

**Comment by TMRh20** [comment]
This looks really good.

**Comment by 2bndy5** [comment]
I haven't mentioned this yet... RTD has a hidden feature that lets you auto-link between different docs hosted by RTD. This means that the user can click the datatype `RF24` in the RF24Network c'tor signiture and inspect the RF24 docs effortlessly. 
![image](https://user-images.githubusercontent.com/14963867/139553671-bbdf6949-59af-4fde-862a-7b6c7cef5fcd.png)

For the life of me, I couldn't get doxygen to do this despite what its manual says about generated tag files 😡 .
