### ISSUE TITLE
NodeMCU library

### ISSUE THREAD

**Issue by OTeknoloji** [nRF24/RF24Network#211]
Hi,
can we use this lib  for esp8266 nodemcu. if answer is that NO, is there alternative lib for nodemcu

**Comment by TMRh20** [comment]
YesOn Jun 14, 2023, at 9:55 AM, OTeknoloji ***@***.***> wrote:﻿
Hi,
can we use this lib  for esp8266 nodemcu. if answer is that NO, is there alternative lib for nodemcu

**Comment by OTeknoloji** [comment]
hi,
 we can use or not use?

**Comment by 2bndy5** [comment]
answer is yes.
