### ISSUE TITLE
Question about system message and network ACK

### ISSUE THREAD

**Issue by jetiston** [nRF24/RF24Network#93]
Hi. So I've read that header type 0-127 are user-defined types, 128-255 are reserved for system. 

I keep receiving a 193 type system message. What does that mean? Is it the network ACK when I send user message with type 65 through 67?

And are there other system messages? and what do they mean? Thanks

**Comment by TMRh20** [comment]
Hmm, apologies for the late reply, but 193 is a Network ACK, which should never be received. It should be discarded by the system.

The system messages if still interested are listed in [RF24Network.h](https://github.com/TMRh20/RF24Network/blob/master/RF24Network.h) and [RF24Mesh.h](https://github.com/TMRh20/RF24Mesh/blob/master/RF24Mesh.h)
