### ISSUE TITLE
Set data rate in RF24Network

### ISSUE THREAD

**Issue by johncarter3** [nRF24/RF24Network#95]
i have a problem using both the RF24 library and the RF24 Network library... the RF24 Network will change the data rate set in the RF24 library to 1MBPS as a default. Meaning if you set the data rate in the RF24 library or if you change the data rate using "radio.setDataRate" prior to calling "network.begin" then the setting will not persist. If you set the data after "network.begin" then the print details will not be accurate the data rate should be whatever was set.

**Comment by TMRh20** [comment]
Hmm, it should be accurate if setting after network.begin, I hope to get a chance to look at this soon.
